apiVersion: v1
kind: PersistentVolume
metadata:
  name: jiraetl
  namespace: jiraetl
spec:
  storageClassName: localstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    # this is the path on laptop?
    path: "/Users/ashujha/mnt/data"
